import assert from 'node:assert/strict'
import {financeStore} from '../lib/finance-store'
import {customerSummary,invoiceBalance} from '../lib/finance-engine'
financeStore.reset()
let snapshot=financeStore.getSnapshot()
const original=customerSummary(snapshot,'cust-1')
const p=financeStore.createPayment({customerId:'cust-1',date:'2026-10-01',amount:100,currency:'OMR',method:'Bank',treatment:'advance',reference:'A-1',description:'Advance without invoice'})
assert.equal(customerSummary(financeStore.getSnapshot(),'cust-1').advanceBalance,100)
assert.throws(()=>financeStore.createPayment({customerId:'cust-1',date:'2026-10-01',amount:100,currency:'OMR',method:'Bank',treatment:'advance',reference:'A-1',description:'Duplicate'}),/Duplicate/)
assert.throws(()=>financeStore.allocatePayment(p.id,[{invoiceId:'inv-913-2024',amount:100}]),/belong/)
assert.throws(()=>financeStore.allocatePayment(p.id,[{invoiceId:'inv-1250-2026',amount:101}]),/available/)
financeStore.allocatePayment(p.id,[{invoiceId:'inv-1250-2026',amount:75}])
assert.equal(customerSummary(financeStore.getSnapshot(),'cust-1').advanceBalance,25)
assert.equal(invoiceBalance(financeStore.getSnapshot(),'inv-1250-2026'),original.totalInvoiced-75)
financeStore.reversePayment(p.id,'Bank returned payment')
assert.equal(invoiceBalance(financeStore.getSnapshot(),'inv-1250-2026'),original.totalInvoiced)
assert.equal(financeStore.getSnapshot().payments.find(x=>x.id===p.id)?.reversalReason,'Bank returned payment')
assert.equal(financeStore.getSnapshot().allocations.filter(a=>a.paymentId===p.id).length,1)
assert.throws(()=>financeStore.allocatePayment(p.id,[{invoiceId:'inv-1250-2026',amount:1}]),/Active/)
assert.throws(()=>financeStore.createPayment({customerId:'cust-1',date:'2026-10-01',amount:10,currency:'USD',method:'Cash',treatment:'other',reference:'USD',description:'USD'}),/Only OMR/)
assert.equal(customerSummary(snapshot,'cust-1').advanceBalance,0)
console.log('Store standalone receipt, allocation, reversal, immutable history and integrity guards pass')
// Historical Paid flags settle accounts but do not provide evidence of cash/date/method.
const migrated=financeStore.getSnapshot()
assert.equal(migrated.payments.filter(p=>p.legacy).length,0)
assert.ok(migrated.transactions.some(t=>t.reference.startsWith('LEGACY-')&&t.amount<0))
assert.equal(customerSummary(migrated,'cust-2').totalPaid,0)
assert.throws(()=>financeStore.createPayment({customerId:'cust-1',date:'2026-02-30',amount:1,currency:'OMR',method:'Bank',treatment:'other',reference:'BAD-DATE',description:'Invalid'}),/Valid/)
assert.throws(()=>financeStore.createPayment({customerId:'cust-1',date:'2026-10-01',amount:1,currency:'OMR',method:'',treatment:'other',reference:'NO-METHOD',description:'Invalid'}),/method/)
const targetPayment=financeStore.createPayment({customerId:'cust-1',date:'2026-10-01',amount:10,currency:'OMR',method:'Bank',treatment:'unallocated',reference:'TARGET-CHECK',description:'Allocation target checks'})
assert.throws(()=>financeStore.allocatePayment(targetPayment.id,[{invoiceId:'inv-1250-2026',transactionId:'anything',amount:1}]),/exactly one/)
assert.throws(()=>financeStore.allocatePayment(targetPayment.id,[{amount:1}]),/exactly one/)
console.log('Legacy settlement excludes invented cash; invalid dates/methods/ambiguous targets rejected')
const validReceipt={customerId:'cust-1',date:'2026-10-01',amount:10,currency:'OMR',method:'Bank',treatment:'unallocated' as const,reference:'NEW',description:'Validation'}
assert.throws(()=>financeStore.createPayment({...validReceipt,reference:' a-1 '}),/Duplicate/)
assert.throws(()=>financeStore.createPayment({...validReceipt,treatment:'invoice'}),/requires an invoice/)
assert.throws(()=>financeStore.createPayment({...validReceipt,treatment:'partial'}),/requires an invoice/)
assert.throws(()=>financeStore.createPayment({...validReceipt,treatment:'opening_balance'}),/requires an opening/)
assert.throws(()=>financeStore.createPayment({...validReceipt,method:'Unknown'}),/method/)
assert.throws(()=>financeStore.createPayment({...validReceipt,method:'Cheque'}),/Cheque number/)
financeStore.addTransaction({customerId:'cust-1',date:'2026-10-01',type:'debit_note',amount:1,description:'Ref test',reference:' dn-unique '})
assert.throws(()=>financeStore.addTransaction({customerId:'cust-1',date:'2026-10-01',type:'debit_note',amount:1,description:'Ref test',reference:'DN-UNIQUE'}),/Duplicate/)
console.log('Treatment allocations, normalized references, method enum and cheque number guards pass')
