"use client"
import { useState } from "react"
import Link from "next/link"
import { useFinance } from "@/lib/finance-view"
import { accountDocuments, type CustomerRecordKind } from "@/lib/account-documents"
import { Button } from "@/components/ui/button"
/** Commercial documents are account attachments, never posted revenue or receipts. */
export function CustomerDocumentSave({ kind, reference, date, data }: {kind:CustomerRecordKind;reference:string;date:string;data:object}) {
 const snapshot=useFinance();const [customerId,setCustomerId]=useState("");const [message,setMessage]=useState("");const [parentRecordId,setParentRecordId]=useState("");
 return <section className="mb-4 flex flex-wrap items-center gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 print:hidden"><label className="text-sm font-medium">Save commercial document to customer account <select aria-label="Customer for commercial document" className="ml-2 rounded-lg border bg-white p-2" value={customerId} onChange={e=>{setCustomerId(e.target.value);setParentRecordId("");setMessage("")}}><option value="">Select customer…</option>{snapshot?.customers.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select></label>{customerId&&<label className="text-sm">Source / prior document <select aria-label="Source commercial document" className="ml-2 rounded-lg border bg-white p-2" value={parentRecordId} onChange={e=>setParentRecordId(e.target.value)}><option value="">Independent document</option>{accountDocuments.getRecords(customerId).filter(r=>["Quotations","Proforma Invoices","Purchase Orders / Client POs"].includes(r.kind)).map(r=><option key={r.id} value={r.id}>{r.kind}: {r.reference||r.title}</option>)}</select></label>}<Button type="button" disabled={!customerId} variant="outline" onClick={()=>{try{if(!reference.trim())throw new Error("Enter a document reference first.");accountDocuments.addRecord({customerId,kind,title:`${kind}: ${reference}`,reference,date,description:`Saved document snapshot (${reference})`,status:"Saved",parentRecordId:parentRecordId||undefined,payload:data,url:`data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify(data,null,2))}`});setMessage("Document snapshot saved to customer account.")}catch(e){setMessage((e as Error).message)}}}>Save to Customer</Button>{message&&<span role="status" className="text-sm">{message} {customerId&&<Link className="underline" href={`/customers/${customerId}?tab=${encodeURIComponent(kind)}`}>Open customer documents</Link>}</span>}</section>
}
