"use client"
import { useEffect, useState } from "react"
import Link from "next/link"
import { PaymentAllocationDialog } from "@/components/payment-allocation-dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { accountDocuments, type CustomerRecordKind, type CustomerProfile } from "@/lib/account-documents"
import { invoiceStore } from "@/lib/invoice-store"
import { customerSummary, customerLedger, invoiceBalance, paymentRemaining } from "@/lib/finance-engine"
import { useFinance, exportCsv } from "@/lib/finance-view"
const tabs = ["Overview","Account","Transactions","Payments","Invoices","Quotations","Proforma Invoices","Delivery Orders","Purchase Orders / Client POs","Credit Notes","Debit Notes","Statement","Projects","Documents","Contacts","Notes","Activity","Audit","Issues"]
const recordTabs = ["Quotations","Proforma Invoices","Delivery Orders","Purchase Orders / Client POs","Projects","Documents","Contacts","Notes"]
const money=(n:number)=>`OMR ${n.toLocaleString("en-OM",{minimumFractionDigits:3,maximumFractionDigits:3})}`
const inputClass="rounded-lg border border-slate-200 p-2 text-sm"
export function CustomerWorkspace({customerId}:{customerId:string}) {
 const snapshot=useFinance();const [allocationId,setAllocationId]=useState<string|null>(null);const [tab,setTab]=useState("Overview");const [revision,setRevision]=useState(0);const [profile,setProfile]=useState<CustomerProfile>({});const [edit,setEdit]=useState(false);const [add,setAdd]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState(new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Muscat"}));
 useEffect(()=>{const sync=()=>{setProfile(accountDocuments.getProfile(customerId));setRevision(n=>n+1)};sync();return accountDocuments.subscribe(sync)},[customerId]);
 useEffect(()=>{setTab(new URLSearchParams(window.location.search).get("tab")||"Overview")},[]);
 if(!snapshot)return <div className="p-8">Loading customer account…</div>;
 const customer=snapshot.customers.find(c=>c.id===customerId);if(!customer)return <div className="p-8">Customer not found. <Link href="/customers">Return to customers</Link></div>;
 const summary=customerSummary(snapshot,customerId);const ledger=customerLedger(snapshot,customerId);const invoices=snapshot.invoices.filter(i=>i.customerId===customerId);const payments=snapshot.payments.filter(p=>p.customerId===customerId);const records=accountDocuments.getRecords(customerId);const activities=accountDocuments.getActivity(customerId);void revision;
 const statementLedger=customerLedger(snapshot,customerId,to||undefined);const rows=statementLedger.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));const before=statementLedger.filter(r=>from&&r.date<from);const opening=before.at(-1)?.runningBalance||0;const closing=rows.at(-1)?.runningBalance??opening;
 const duplicateReferences=payments.filter((p,index)=>payments.findIndex(other=>other.reference.trim().toLowerCase()===p.reference.trim().toLowerCase())!==index).map(p=>`Duplicate payment reference: ${p.reference}.`);
 const issues=[...snapshot.transactions.filter(t=>t.customerId===customerId&&t.reference.startsWith("LEGACY-")).map(t=>`Unverified historical settlement ${t.reference}: ${money(Math.abs(t.amount))}. Original receipt date and method require reconciliation.`),...duplicateReferences,...(!customer.vatin?["Missing customer VATIN."]:[]),...(!profile.crNumber?["Missing customer CR number."]:[]),...(summary.totalOverdue>0?[`Overdue receivables: ${money(summary.totalOverdue)}.`]:[]),...(summary.unallocatedPayment>0?[`Unallocated receipts: ${money(summary.unallocatedPayment)}. Open Payments to allocate them.`]:[]),...(profile.creditLimit&&summary.totalOutstanding>profile.creditLimit?[`Credit limit exceeded by ${money(summary.totalOutstanding-profile.creditLimit)}.`]:[]),...payments.filter(p=>p.reversedAt).map(p=>`Reversed receipt ${p.reference}; history preserved.`),...invoices.filter(i=>!i.poNumber&&i.status!=="Cancelled"&&!accountDocuments.getDocumentChain(accountDocuments.getInvoiceSource(i.id)?.id||"").some(record=>record.kind==="Purchase Orders / Client POs")).map(i=>`Invoice ${i.invoiceNumber} has no customer PO reference.`)];
 const audits=invoiceStore.getAuditLogs().filter(a=>a.entityId===customerId||invoices.some(i=>i.id===a.entityId)||payments.some(p=>p.id===a.entityId)||snapshot.transactions.some(t=>t.customerId===customerId&&t.id===a.entityId));const lastInvoice=[...invoices].filter(i=>i.invoiceDate<=to&&i.status!=="Draft"&&i.status!=="Cancelled").sort((a,b)=>b.invoiceDate.localeCompare(a.invoiceDate))[0];const lastPayment=[...payments].sort((a,b)=>b.date.localeCompare(a.date))[0];
 const metrics:[string,number,string][]=[["Total Business / Revenue",summary.totalRevenue,"Invoices"],["Total Invoiced",summary.totalInvoiced,"Invoices"],["Total Paid",summary.totalPaid,"Payments"],["Total Outstanding",summary.totalOutstanding,"Account"],["Total Overdue",summary.totalOverdue,"Issues"],["Advance Balance",summary.advanceBalance,"Payments"],["Unallocated Payment",summary.unallocatedPayment,"Payments"],["Credit Balance",summary.creditBalance,"Account"],["Debit Balance",summary.debitBalance,"Account"],["Opening Balance",summary.openingBalance,"Account"],["Current Account Balance",summary.currentAccountBalance,"Account"]];
 const ledgerTable=(data:typeof ledger)=><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["Date","Reference","Type","Description","Debit","Credit","Running Balance","Status"].map(h=><th key={h} className="border-b p-3 text-left">{h}</th>)}</tr></thead><tbody>{data.map(r=><tr key={r.id}><td className="p-3">{r.date}</td><td className="p-3">{r.reference}</td><td className="p-3">{r.type}</td><td className="p-3">{r.description}</td><td className="p-3 whitespace-nowrap">{money(r.debit)}</td><td className="p-3 whitespace-nowrap">{money(r.credit)}</td><td className="p-3 whitespace-nowrap">{money(r.runningBalance)}</td><td className="p-3">{r.status}</td></tr>)}</tbody></table>{!data.length&&<p className="p-5 text-slate-500">No financial transactions in this period.</p>}</div>;
 async function pdf(download=true){try{if(from&&to&&from>to)throw new Error("Statement end date must be on or after start date.");setNotice("Preparing PDF…");const {createStatementPdf}=await import("@/lib/statement-pdf");const settings=invoiceStore.getSettings();let imageData:string|undefined;try{const response=await fetch(settings.letterheadUrl);if(!response.ok)throw new Error("Letterhead unavailable");const blob=await response.blob();imageData=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)})}catch{/* Text company credentials remain available. */}const doc=createStatementPdf({company:settings.companyDetails,customer:customer!,from,to,openingBalance:opening,closingBalance:closing,rows,letterheadData:imageData});if(download){doc.save(`statement-${customer!.id}.pdf`);setNotice("PDF downloaded.")}return doc.output("blob")}catch(e){setError(e instanceof Error?e.message:"PDF failed")}}

 const receipt=async(p:typeof payments[number])=>{const {jsPDF}=await import("jspdf");const doc=new jsPDF();const s=invoiceStore.getSettings();try{const response=await fetch(s.letterheadUrl);if(!response.ok)throw new Error("Letterhead unavailable");const blob=await response.blob();const image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)});doc.addImage(image,"PNG",0,0,210,297)}catch{/* Keep company credentials if image unavailable. */}doc.setFontSize(18);doc.text(s.companyDetails.name,20,45);doc.setFontSize(10);doc.text(`${s.companyDetails.address} | VATIN ${s.companyDetails.vatin}`,20,55);doc.setFontSize(16);doc.text("PAYMENT RECEIPT",20,75);doc.setFontSize(12);doc.text([`Customer: ${customer.companyName}`,`Reference: ${p.reference}`,`Date: ${p.date}`,`Amount: ${p.currency} ${p.amount.toFixed(3)}`,`Method: ${p.method}`,`Treatment: ${p.treatment}`,`Status: ${p.reversedAt?"REVERSED":"Received"}`,`Description: ${p.description}`],20,95);doc.save(`receipt-${p.id}.pdf`)};
 return <main className="min-h-screen bg-slate-50 p-4 pt-28 md:p-8"><div className="mx-auto max-w-7xl space-y-5"><div className="print:hidden"><Link href="/customers" className="text-sm text-amber-700">← Customers</Link></div><header className="flex flex-wrap items-start justify-between gap-3 print:hidden"><div><p className="text-sm text-slate-500">Customer 360° · {profile.customerCode||customer.id}</p><h1 className="text-3xl font-bold">{customer.companyName}</h1><p className="text-slate-500">{profile.accountStatus||"Active"} · Created {new Date(customer.createdAt).toLocaleDateString()} · Last activity {new Date(Math.max(customer.updatedAt,...activities.map(a=>a.timestamp),...payments.map(p=>p.createdAt),...invoices.filter(i=>i.invoiceDate<=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Muscat"})).map(i=>i.updatedAt))).toLocaleDateString()}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setEdit(!edit)}>Edit Account Details</Button><Button onClick={()=>setTab("Issues")} variant="outline">Account Issues: {issues.length}</Button><Button asChild className="bg-amber-600"><Link href={`/finance/payments/new?customer=${customerId}`}>Add Payment</Link></Button></div></header>
 {error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {edit&&<form className="grid gap-3 rounded-xl bg-white p-5 md:grid-cols-3" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);invoiceStore.updateCustomer(customerId,{companyName:String(fields.get("companyName")).trim(),address:String(fields.get("address")||""),phone:String(fields.get("phone")||""),email:String(fields.get("email")||""),poBox:String(fields.get("poBox")||""),vatin:String(fields.get("vatin")||"")});accountDocuments.saveProfile(customerId,profile);setEdit(false)}}>{(["companyName","address","phone","email","poBox","vatin"] as const).map(key=><label key={key} className="text-sm">{key.replace(/([A-Z])/g," $1")}<Input name={key} defaultValue={customer[key]||""} required={key==="companyName"} type={key==="email"?"email":"text"}/></label>)}{["customerCode","crNumber","customerType","contactPerson","paymentTerms","accountStatus"].map(key=><label key={key} className="text-sm">{key.replace(/([A-Z])/g," $1")}<Input value={String(profile[key as keyof CustomerProfile]||"")} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<label>Credit Limit (OMR)<Input type="number" min="0" step="0.001" value={profile.creditLimit??""} onChange={e=>setProfile({...profile,creditLimit:Number(e.target.value)})}/></label><Button type="submit">Save Account Details</Button></form>}
 <nav className="flex flex-wrap gap-1 rounded-xl border bg-white p-2 print:hidden" aria-label="Customer workspace">{tabs.map(t=><button key={t} onClick={()=>{setTab(t);setAdd(false)}} className={`rounded-lg px-3 py-2 text-sm ${t===tab?"bg-amber-100 font-semibold text-amber-900":"text-slate-600 hover:bg-slate-100"}`}>{t}</button>)}</nav>
 <section className="rounded-xl border bg-white p-5">
 {(tab==="Overview"||tab==="Account")&&<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,target])=><button key={label} onClick={()=>setTab(target)} className="rounded-xl border p-4 text-left hover:border-amber-400"><div className="text-xs text-slate-500">{label}</div><div className="mt-2 text-xl font-bold">{money(value)}</div></button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><h2 className="font-semibold">Customer Information</h2><dl className="mt-3 grid grid-cols-2 gap-2 text-sm">{Object.entries({"Customer Name":customer.companyName,"Company Name":customer.companyName,"Code":profile.customerCode||customer.id,"CR":profile.crNumber,"VATIN":customer.vatin,"Type":profile.customerType,"Contact Person":profile.contactPerson,"Phone":customer.phone,"Email":customer.email,"Address":customer.address,"P.O. Box":customer.poBox,"Terms":profile.paymentTerms||lastInvoice?.paymentTerms,"Credit Limit":profile.creditLimit===undefined?"Not configured":money(profile.creditLimit),"Account Status":profile.accountStatus||"Active","Last Invoice":lastInvoice?.invoiceNumber,"Last Payment":lastPayment?.date,"Average Payment Time":summary.averagePaymentTime===null?"Unavailable until payments are allocated":`${summary.averagePaymentTime} days`}).map(([k,v])=><div key={k}><dt className="text-slate-500">{k}</dt><dd>{v||"Not supplied"}</dd></div>)}</dl></div><div><h2 className="font-semibold">Recent Activity</h2>{activities.slice(-6).reverse().map(a=><p key={a.id} className="border-b py-2 text-sm">{new Date(a.timestamp).toLocaleString()} · {a.description}</p>)}{!activities.length&&<p className="text-sm text-slate-500">No account metadata activity recorded.</p>}</div></div><h2 className="mt-6 font-semibold">{tab==="Account"?"Complete Account Ledger":"Recent Transactions"}</h2>{ledgerTable(tab==="Account"?ledger:ledger.slice(-8))}</>}
 {tab==="Transactions"&&ledgerTable(ledger)}
 {tab==="Invoices"&&<div className="space-y-2">{invoices.map(i=>{const source=accountDocuments.getInvoiceSource(i.id);return <article key={i.id} className="rounded border p-3"><Link href={`/invoices/${i.id}`} className="flex justify-between"><span>{i.invoiceNumber} · {i.invoiceDate} · {i.status}</span><span>{money(i.total)} · Balance {money(invoiceBalance(snapshot,i.id))}</span></Link><div className="mt-3 flex flex-wrap items-center gap-3 text-sm"><label>Source Document <select aria-label={`Source for invoice ${i.invoiceNumber}`} className="ml-2 rounded border p-2" value={source?.id||""} onChange={e=>{try{accountDocuments.assignInvoiceSource(customerId,i.id,e.target.value);setError("")}catch(err){setError((err as Error).message)}}}><option value="">Independent invoice</option>{records.filter(r=>["Quotations","Proforma Invoices","Purchase Orders / Client POs"].includes(r.kind)).map(r=><option key={r.id} value={r.id}>{r.kind}: {r.reference||r.title}</option>)}</select></label>{source&&<span>{accountDocuments.getDocumentChain(source.id).map(r=><span key={r.id}><Link className="text-amber-700 underline" onClick={()=>setTab(r.kind)} href={`/customers/${customerId}?tab=${encodeURIComponent(r.kind)}#record-${r.id}`}>{r.reference||r.title}</Link> → </span>)}{i.invoiceNumber} → <button className="text-amber-700 underline" onClick={()=>setTab("Payments")}>Payment Allocations ({snapshot.allocations.filter(a=>a.invoiceId===i.id).length})</button></span>}</div></article>})}{!invoices.length&&<p>No invoices. Payments can be received before an invoice exists.</p>}</div>}

 {tab==="Payments"&&<div className="space-y-3">{payments.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-3 rounded border p-4"><div><p className="font-semibold">{p.reference} · {money(p.amount)}</p><p className="text-sm">{p.date} · {p.method} · {p.treatment} · {p.reversedAt?"Reversed":"Received"}</p><p className="text-sm text-slate-500">{p.description}</p>{p.attachment&&<a href={p.attachment} target="_blank" rel="noopener noreferrer" download={`proof-${p.reference}`} className="text-xs text-emerald-700 underline">Payment proof</a>}</div><div className="flex flex-wrap gap-2">{!p.reversedAt&&paymentRemaining(snapshot,p)>0&&<Button variant="outline" onClick={()=>setAllocationId(p.id)}>{p.treatment==="advance"?"Apply Existing Advance":"Allocate Payment"}</Button>}<Button variant="outline" onClick={()=>receipt(p).catch(e=>setError(String(e)))}>Receipt PDF</Button><Button asChild variant="outline"><Link href={`/finance/payments?customer=${customerId}&payment=${p.id}`}>Allocations / Reversal</Link></Button></div></div>)}{!payments.length&&<p>No payments yet. <Link className="text-amber-700" href={`/finance/payments/new?customer=${customerId}`}>Record a standalone payment</Link>.</p>}</div>}
 {(tab==="Credit Notes"||tab==="Debit Notes")&&<><Button asChild><Link href={`/finance/${tab==="Credit Notes"?"credit-notes":"debit-notes"}?customer=${customerId}`}>Add {tab.slice(0,-1)}</Link></Button>{ledgerTable(ledger.filter(r=>r.type.toLowerCase().replaceAll("_"," ").includes(tab==="Credit Notes"?"credit note":"debit note")))}</>}
 {recordTabs.includes(tab)&&<><div className="flex items-center justify-between"><h2 className="font-semibold">{tab}</h2><Button onClick={()=>setAdd(!add)}>Add {tab==="Contacts"?"Contact":tab==="Projects"?"Project":"Record"}</Button></div>{add&&<form className="my-4 grid gap-3 rounded bg-slate-50 p-4 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);try{let url=String(f.get("url")||"");const file=f.get("file") as File;if(file?.size){if(file.size>2_000_000)throw new Error("Attachment must be under 2 MB in this local workspace.");url=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)})}if(url&&!url.startsWith("data:")&&!/^https?:\/\//i.test(url))throw new Error("Use an http or https attachment URL.");accountDocuments.addRecord({customerId,kind:tab as CustomerRecordKind,title:String(f.get("title")),reference:String(f.get("reference")||""),description:String(f.get("description")||""),date:String(f.get("date")),email:String(f.get("email")||""),phone:String(f.get("phone")||""),status:String(f.get("status")),parentRecordId:String(f.get("parentRecordId")||"")||undefined,url});setAdd(false);setError("")}catch(err){setError(err instanceof Error?err.message:String(err))}}}>
 <Input name="title" placeholder="Name / title" required/><Input name="reference" placeholder="Document / project reference"/>{["Quotations","Proforma Invoices","Delivery Orders","Purchase Orders / Client POs","Documents"].includes(tab)&&<select name="parentRecordId" aria-label="Prior customer document" className="rounded border p-2 text-sm"><option value="">Independent document</option>{records.filter(r=>["Quotations","Proforma Invoices","Purchase Orders / Client POs"].includes(r.kind)).map(r=><option key={r.id} value={r.id}>{r.kind}: {r.reference||r.title}</option>)}</select>}<Input type="date" name="date" defaultValue={to} required/><Input name="status" defaultValue="Active" placeholder="Status"/><Input name="description" placeholder="Description / internal note"/>{tab==="Contacts"&&<><Input name="email" type="email" placeholder="Email"/><Input name="phone" placeholder="Phone"/></>}{tab!=="Notes"&&<><Input name="url" placeholder="Attachment https:// URL"/><Input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.xlsx"/></>}<Button type="submit">Save Customer Record</Button></form>}
 {tab==="Projects"&&<div className="my-4 rounded-xl border p-4"><h3 className="font-semibold">Invoice Revenue Attribution</h3><p className="my-2 text-sm text-slate-500">Assign posted invoices to a customer project for the Revenue by Project report. The financial amounts remain derived from the invoice and its notes.</p>{invoices.filter(i=>i.status!=="Draft"&&i.status!=="Cancelled").map(i=><label className="flex flex-wrap items-center justify-between gap-2 border-b py-3 text-sm" key={i.id}><span>{i.invoiceNumber} · Revenue {money(i.taxableValue)}</span><select aria-label={`Project for invoice ${i.invoiceNumber}`} className="rounded border p-2" value={accountDocuments.getInvoiceProject(i.id)?.id||""} onChange={e=>{try{accountDocuments.assignInvoiceProject(customerId,i.id,e.target.value);setError("")}catch(err){setError((err as Error).message)}}}><option value="">Unassigned</option>{records.filter(r=>r.kind==="Projects").map(r=><option key={r.id} value={r.id}>{r.title} ({r.reference||r.id.slice(0,8)})</option>)}</select></label>)}</div>}
 <div className="mt-4 space-y-2">{tab==="Documents"&&payments.filter(p=>p.attachment).map(p=><a key={p.id} href={p.attachment} target="_blank" rel="noopener noreferrer" download={`proof-${p.reference}`} className="block rounded border p-3 text-sm text-emerald-700">Payment proof · {p.reference} · {p.date}</a>)}{records.filter(r=>r.kind===tab).map(r=><article key={r.id} id={`record-${r.id}`} className="rounded border p-3"><div className="flex justify-between"><h3 className="font-semibold">{r.title}</h3><span className="text-sm text-slate-500">{r.date} · {r.status}</span></div><p className="text-sm">{r.reference} {r.description}</p>{r.parentRecordId&&<p className="mt-2 text-xs">Document chain: {accountDocuments.getDocumentChain(r.id).map((document,index)=><span key={document.id}>{index>0&&" → "}<Link className="text-amber-700 underline" onClick={()=>setTab(document.kind)} href={`/customers/${customerId}?tab=${encodeURIComponent(document.kind)}#record-${document.id}`}>{document.reference||document.title}</Link></span>)}</p>}{r.email&&<a href={`mailto:${r.email}`} className="mr-3 text-amber-700">{r.email}</a>}{r.phone&&<span>{r.phone}</span>}{r.url&&<a className="ml-3 text-amber-700 underline" href={r.url} target="_blank" rel="noopener noreferrer" download={r.url.startsWith("data:")?r.title:undefined}>Open Attachment</a>}</article>)}{!records.some(r=>r.kind===tab)&&<p className="text-sm text-slate-500">No {tab.toLowerCase()} linked to this customer. Add a customer record above.</p>}</div></>}
 {tab==="Issues"&&<div className="space-y-2"><h2 className="font-semibold">Financial / Account Exceptions ({issues.length})</h2>{issues.map((issue,i)=><p key={i} className="rounded border border-amber-200 bg-amber-50 p-3">{issue}</p>)}{!issues.length&&<p>No account exceptions found.</p>}</div>}
 {(tab==="Activity"||tab==="Audit")&&<div className="space-y-2">{[...activities.map(a=>({id:a.id,timestamp:a.timestamp,description:a.description,action:a.action})),...audits,...ledger.map(r=>({id:r.id,timestamp:new Date(r.date).getTime(),description:`${r.reference}: ${r.description} (${r.status})`,action:r.type}))].sort((a,b)=>b.timestamp-a.timestamp).map(a=><p key={a.id} className="border-b p-3 text-sm"><span className="font-mono text-slate-500">{new Date(a.timestamp).toLocaleString()}</span> · {a.action}<br/>{a.description}</p>)}</div>}
 {tab==="Statement"&&<><div className="mb-4 flex flex-wrap gap-2 print:hidden"><label className="text-sm">From <input aria-label="Statement start date" className={inputClass} type="date" max={to||undefined} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">To <input aria-label="Statement end date" className={inputClass} type="date" min={from||undefined} value={to} onChange={e=>setTo(e.target.value)}/></label><Button variant="outline" onClick={()=>window.print()}>Print A4</Button><Button variant="outline" onClick={()=>pdf()}>PDF</Button><Button variant="outline" onClick={()=>exportCsv(`statement-${customerId}`,["Date","Reference","Type","Description","Debit OMR","Credit OMR","Running Balance OMR","Status"],[[from,"","Opening Balance","",0,0,opening.toFixed(3),""],...rows.map(r=>[r.date,r.reference,r.type,r.description,r.debit.toFixed(3),r.credit.toFixed(3),r.runningBalance.toFixed(3),r.status]),[to,"","Closing Balance","",0,0,closing.toFixed(3),""]])}>Export CSV</Button><Button variant="outline" onClick={async()=>{const text=`Golden Hornet LLC — Statement of Account\n${customer.companyName}\n${from||"Beginning"} to ${to}\nOpening ${money(opening)}\nClosing ${money(closing)}`;try{const blob=await pdf(false);const file=blob?new File([blob],`statement-${customerId}.pdf`,{type:"application/pdf"}):null;if(file&&navigator.canShare?.({files:[file]}))await navigator.share({title:"Statement of Account",text,files:[file]});else if(navigator.share)await navigator.share({title:"Statement of Account",text});else {await navigator.clipboard.writeText(text);setNotice("Statement summary copied; use PDF to attach the full statement.")}}catch(e){setError(String(e))}}}>Share</Button></div>
 <article id="account-statement" className="relative mx-auto min-h-[297mm] max-w-[210mm] bg-white px-8 pb-20 pt-28 text-slate-900" style={{backgroundImage:`url('${invoiceStore.getSettings().letterheadUrl}')`,backgroundSize:"100% 297mm",backgroundRepeat:"no-repeat"}}><div className="border border-slate-900 bg-white/95 p-4"><h2 className="font-bold">{invoiceStore.getSettings().companyDetails.name}</h2><p className="text-xs">{invoiceStore.getSettings().companyDetails.address} · VATIN {invoiceStore.getSettings().companyDetails.vatin}</p><h3 className="my-4 border-y border-slate-900 py-2 text-center font-bold uppercase tracking-widest">Statement of Account</h3><p className="font-semibold">Customer: {customer.companyName}</p><p className="text-sm">{customer.address} · VATIN {customer.vatin||"Not supplied"}</p><p className="my-3 text-sm">Period: {from||"Beginning of account"} — {to||"Present"}</p><p className="font-semibold">Opening Balance: {money(opening)}</p>{ledgerTable(rows)}<p className="mt-4 border-t pt-3 text-right text-lg font-bold">Closing Balance: {money(closing)}</p><p className="mt-5 text-xs text-slate-500">Allocation entries are noncash movements and do not duplicate payment credits. Positive closing balance is payable by the customer; negative balance is customer credit.</p></div></article>
 <style>{`@media print {body * {visibility:hidden} #account-statement,#account-statement * {visibility:visible} #account-statement {position:absolute;left:0;top:0;width:210mm;max-width:none} @page {size:A4;margin:0} tr {break-inside:avoid} thead {display:table-header-group}}`}</style></>}
 </section>{allocationId&&<PaymentAllocationDialog paymentId={allocationId} onClose={()=>setAllocationId(null)}/>}</div></main>
}
