"use client"
import { useState } from "react"
import { X } from "lucide-react"
import { financeStore } from "@/lib/finance-store"
import { useFinance } from "@/lib/finance-view"
import { invoiceBalance, paymentRemaining } from "@/lib/finance-engine"
import { formatOMR } from "@/lib/financial-calculator"
export function PaymentAllocationDialog({paymentId,onClose}:{paymentId:string;onClose:()=>void}) {
 const snapshot=useFinance();const [values,setValues]=useState<Record<string,string>>({});const [error,setError]=useState("")
 if(!snapshot)return null;const payment=snapshot.payments.find(p=>p.id===paymentId);if(!payment)return null
 const invoices=snapshot.invoices.filter(i=>i.customerId===payment.customerId&&invoiceBalance(snapshot,i.id)>0)
 const debits=snapshot.transactions.filter(t=>t.customerId===payment.customerId&&!t.invoiceId&&["opening_balance","debit_note","adjustment"].includes(t.type)&&t.amount>0)
 const total=Object.values(values).reduce((s,v)=>s+Math.round(Number(v||0)*1000),0)/1000
 return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/40 p-4"><section role="dialog" aria-modal="true" aria-label="Allocate payment" className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between"><h2 className="text-lg font-bold">Allocate {payment.reference}</h2><button aria-label="Close" onClick={onClose}><X size={18}/></button></div><p className="my-4 text-sm text-slate-500">Available OMR <strong>{formatOMR(paymentRemaining(snapshot,payment))}</strong> · no new money is recorded.</p>{[...invoices.map(i=>({id:i.id,reference:i.invoiceNumber,balance:invoiceBalance(snapshot,i.id),kind:"invoice"})),...debits.map(t=>({id:t.id,reference:t.reference,balance:t.amount-snapshot.allocations.filter(a=>a.transactionId===t.id&&snapshot.payments.some(p=>p.id===a.paymentId&&!p.reversedAt)).reduce((s,a)=>s+a.amount,0),kind:"transaction"}))].filter(r=>r.balance>0).map(r=><label key={r.id} className="flex items-center justify-between gap-3 border-b py-3 text-sm"><span>{r.reference}<span className="ml-3 text-xs text-slate-500">Open {formatOMR(r.balance)}</span></span><input aria-label={`Amount for ${r.reference}`} type="number" min="0" step="0.001" max={r.balance} value={values[r.id]||""} onChange={e=>setValues({...values,[r.id]:e.target.value})} placeholder="0.000" className="w-36 rounded-lg border p-2"/></label>)}<p className="my-4 text-sm">Allocation total OMR {formatOMR(total)}</p>{error&&<p role="alert" className="mb-4 text-sm text-red-700">{error}</p>}<button className="rounded-lg bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white" onClick={()=>{try{const rows=Object.entries(values).filter(([,v])=>Number(v)>0).map(([id,v])=>invoices.some(i=>i.id===id)?{invoiceId:id,amount:Number(v)}:{transactionId:id,amount:Number(v)});if(!rows.length)throw new Error("Enter an allocation amount");financeStore.allocatePayment(payment.id,rows);onClose()}catch(e){setError((e as Error).message)}}}>Apply allocation</button></section></div>
}
