'use client'
import { normalizedReference, normalizedPaymentMethod } from './finance-validation'
import { invoiceStore } from './invoice-store'
import { accountDocuments } from './account-documents'
import { invoiceBalance, paymentRemaining, toBaisa, fromBaisa, type FinanceSnapshot, type Payment, type PaymentAllocation, type FinancialTransaction, type Expense } from './finance-engine'
export type { FinanceSnapshot, Payment, PaymentAllocation, FinancialTransaction, Expense, PaymentTreatment } from './finance-engine'
export type PaymentInput = Omit<Payment,'id'|'createdAt'|'reversedAt'|'reversalReason'> & { allocations?:AllocationInput[] }
export interface AllocationInput { invoiceId?:string; transactionId?:string; amount:number }
const KEY='gh:finance:v1'
type State={payments:Payment[];allocations:PaymentAllocation[];transactions:FinancialTransaction[];expenses:Expense[];migrated:string[]}
const empty=():State=>({payments:[],allocations:[],transactions:[],expenses:[],migrated:[]})
const uid=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,10)}`
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Muscat'})
const validDate=(date:string)=> /^\d{4}-\d{2}-\d{2}$/.test(date) && Number.isFinite(new Date(date+'T00:00:00Z').getTime()) && new Date(date+'T00:00:00Z').toISOString().slice(0,10)===date
class FinanceStore {
 private listeners=new Set<()=>void>(); private memory=empty()
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);const off=invoiceStore.subscribe(listener);return()=>{this.listeners.delete(listener);off()}}
 private read():State {if(typeof window==='undefined')return structuredClone(this.memory);const stored=localStorage.getItem(KEY);if(!stored)return empty();return {...empty(),...JSON.parse(stored)}}
 private write(state:State){if(typeof window!=='undefined')localStorage.setItem(KEY,JSON.stringify(state));else this.memory=state;this.listeners.forEach(l=>l())}
 reset(){this.write(empty())}
 getSnapshot():FinanceSnapshot {
  const state=this.read();const invoices=invoiceStore.getInvoices();let changed=false
  // Legacy paid flags are settlement evidence, never evidence of bank/cash collection.
  for(const p of state.payments.filter(p=>p.legacy)) {
   const allocations=state.allocations.filter(a=>a.paymentId===p.id)
   for(const a of allocations){const id=`legacy-settlement-${a.invoiceId}`;if(!state.transactions.some(t=>t.id===id))state.transactions.push({id,customerId:p.customerId,date:p.date,type:'adjustment',amount:-a.amount,invoiceId:a.invoiceId,reference:p.reference,description:'Migrated historical invoice settlement; receipt date/method unverified. Not counted as cash received.',createdAt:p.createdAt})}
   changed=true
  }
  const legacyIds=new Set(state.payments.filter(p=>p.legacy).map(p=>p.id));state.payments=state.payments.filter(p=>!p.legacy);state.allocations=state.allocations.filter(a=>!legacyIds.has(a.paymentId))
  const migratedIds=new Set(state.migrated)
  for(const i of invoices){if(migratedIds.has(i.id))continue;state.migrated.push(i.id);migratedIds.add(i.id);changed=true;const paid=i.status==='Paid'?i.total:(i.paidAmount||0);if(paid>0&&i.customerId&&i.status!=='Draft'&&i.status!=='Cancelled'){const id=`legacy-settlement-${i.id}`;if(!state.transactions.some(t=>t.id===id))state.transactions.push({id,customerId:i.customerId,date:i.invoiceDate,type:'adjustment',amount:-paid,invoiceId:i.id,reference:`LEGACY-${i.invoiceNumber}`,description:'Migrated historical invoice settlement; receipt date/method unverified. Not counted as cash received.',createdAt:i.createdAt})}}
  if(changed){if(typeof window!=='undefined')localStorage.setItem(KEY,JSON.stringify(state));else this.memory=state}
  return Object.freeze({customers:invoiceStore.getCustomers().map(c=>({...c,accountStatus:accountDocuments.getProfile(c.id).accountStatus||"Active"})),invoices,...state})
 }
 private validateAllocations(s:FinanceSnapshot,p:Payment,inputs:AllocationInput[],date:string) {
  const amounts=new Map<string,number>();let total=0
  for(const a of inputs){if(Boolean(a.invoiceId)===Boolean(a.transactionId))throw new Error('Select exactly one allocation target');const amount=toBaisa(a.amount);if(amount<=0)throw new Error('Allocation amount must be positive');total+=amount;if(a.invoiceId){const invoice=s.invoices.find(i=>i.id===a.invoiceId);if(!invoice||invoice.customerId!==p.customerId)throw new Error('Invoice must belong to payment customer');if(invoice.currency!==p.currency)throw new Error('Allocation currency must match invoice');if(invoice.status==='Draft'||invoice.status==='Cancelled'||invoice.invoiceDate>date)throw new Error('Only posted invoices can receive allocations');const used=(amounts.get(a.invoiceId)||0)+amount;amounts.set(a.invoiceId,used);if(used>toBaisa(invoiceBalance(s,a.invoiceId,date)))throw new Error('Allocation exceeds invoice outstanding')}else{const target=s.transactions.find(t=>t.id===a.transactionId&&t.customerId===p.customerId&&t.date<=date&&['opening_balance','debit_note','adjustment','refund'].includes(t.type));if(!target||target.amount<=0)throw new Error('Select an opening balance or account debit');if(target.invoiceId)throw new Error('Allocate invoice-linked debits through their invoice');const used=(amounts.get(target.id)||0)+amount;amounts.set(target.id,used);const prior=s.allocations.filter(x=>x.transactionId===target.id&&s.payments.some(p=>p.id===x.paymentId&&!p.reversedAt)).reduce((n,x)=>n+toBaisa(x.amount),0);if(used+prior>toBaisa(target.amount))throw new Error('Allocation exceeds account debit')}}
  if(total>toBaisa(paymentRemaining(s,p,date)))throw new Error('Allocation exceeds available payment')
 }
 createPayment(input:PaymentInput):Payment {
  const s=this.getSnapshot();if(!s.customers.some(c=>c.id===input.customerId))throw new Error('Customer not found');if(input.currency!=='OMR')throw new Error('Only OMR receipts supported; foreign currency requires exchange rates');if(toBaisa(input.amount)<=0)throw new Error('Payment amount must be positive');if(!validDate(input.date)||input.date>today())throw new Error('Valid payment date required (cannot be future dated)');if(!input.reference.trim())throw new Error('Payment reference required');if(s.payments.some(p=>normalizedReference(p.reference)===normalizedReference(input.reference)&&p.customerId===input.customerId))throw new Error('Duplicate customer payment reference');if(!input.method.trim())throw new Error('Payment method required');if(!['invoice','partial','advance','unallocated','account','opening_balance','other'].includes(input.treatment))throw new Error('Invalid payment treatment');const {allocations=[],...data}=input;const method=normalizedPaymentMethod(data.method);if(method==='Cheque'&&!data.chequeNumber?.trim())throw new Error('Cheque number required');if(['invoice','partial'].includes(data.treatment)&&!allocations.some(a=>a.invoiceId&&a.amount>0))throw new Error('Invoice or partial treatment requires an invoice allocation');if(data.treatment==='opening_balance'&&!allocations.some(a=>a.amount>0&&s.transactions.some(t=>t.id===a.transactionId&&t.type==='opening_balance')))throw new Error('Opening balance treatment requires an opening balance allocation');const p:Payment={...data,reference:normalizedReference(data.reference),method,amount:fromBaisa(toBaisa(data.amount)),id:uid('pay'),createdAt:Date.now()};const next={...s,payments:[...s.payments,p]};this.validateAllocations(next,p,allocations,p.date);const state=this.read();state.payments.push(p);state.allocations.push(...allocations.map(a=>({...a,id:uid('alloc'),paymentId:p.id,date:p.date,createdAt:Date.now()})));this.write(state);invoiceStore.logFinanceActivity("PAYMENT_RECEIVED","payment",p.id,`Received ${p.amount.toFixed(3)} OMR from customer ${p.customerId}; reference ${p.reference}`,p);return p
 }
 allocatePayment(id:string,inputs:AllocationInput[],date=today()) {const s=this.getSnapshot();const p=s.payments.find(p=>p.id===id);if(!p||p.reversedAt)throw new Error('Active payment required');if(!validDate(date)||date<p.date||date>today())throw new Error('Allocation date must follow receipt and cannot be future dated');this.validateAllocations(s,p,inputs,date);const state=this.read();const rows=inputs.map(a=>({...a,id:uid('alloc'),paymentId:id,date,createdAt:Date.now()}));state.allocations.push(...rows);this.write(state);invoiceStore.logFinanceActivity("PAYMENT_ALLOCATED","payment",id,`Allocated receipt ${id}`,rows);return rows}
 reversePayment(id:string,reason:string,date=today()){const s=this.getSnapshot();const p=s.payments.find(p=>p.id===id);if(!p||p.reversedAt)throw new Error('Active payment required');if(!reason.trim())throw new Error('Reversal reason required');if(!validDate(date)||date<p.date||date>today())throw new Error('Invalid reversal date');const state=this.read();state.payments=state.payments.map(x=>x.id===id?{...x,reversedAt:date,reversalReason:reason}:x);this.write(state);invoiceStore.logFinanceActivity("PAYMENT_REVERSED","payment",id,reason,{date,reason})}
 addTransaction(input:Omit<FinancialTransaction,'id'|'createdAt'>){const s=this.getSnapshot();if(!validDate(input.date)||input.date>today())throw new Error('Valid transaction date required');if(!s.customers.some(c=>c.id===input.customerId))throw new Error('Customer not found');if(input.vatAmount!==undefined&&(input.vatAmount<0||input.vatAmount>Math.abs(input.amount)))throw new Error('Invalid VAT amount');if(input.type==='reversal')throw new Error('Use reversal operation for an existing payment');if(toBaisa(input.amount)===0)throw new Error('Amount required');if(input.type!=='adjustment'&&input.type!=='opening_balance'&&input.amount<0)throw new Error('Amount must be positive');if(input.invoiceId){const i=s.invoices.find(i=>i.id===input.invoiceId&&i.customerId===input.customerId);if(!i||i.status==='Draft'||i.status==='Cancelled'||input.date<i.invoiceDate)throw new Error('Posted customer invoice required');if(input.type==='credit_note'&&toBaisa(input.amount)+s.transactions.filter(t=>t.invoiceId===i.id&&t.type==='credit_note').reduce((n,t)=>n+toBaisa(t.amount),0)>toBaisa(i.total))throw new Error('Credit exceeds invoice total')}if(!input.reference.trim())throw new Error('Reference required');if(s.transactions.some(t=>t.customerId===input.customerId&&t.type===input.type&&normalizedReference(t.reference)===normalizedReference(input.reference)))throw new Error('Duplicate customer transaction reference');const row={...input,reference:normalizedReference(input.reference),amount:fromBaisa(toBaisa(input.amount)),id:uid('txn'),createdAt:Date.now()};const state=this.read();state.transactions.push(row);this.write(state);invoiceStore.logFinanceActivity("TRANSACTION_POSTED","transaction",row.id,row.description,row);return row}
 addExpense(input:Omit<Expense,'id'|'createdAt'>){if(!validDate(input.date)||input.date>today())throw new Error('Valid expense date required');if(toBaisa(input.amount)<=0||toBaisa(input.vatAmount)<0||input.vatAmount>input.amount)throw new Error('Invalid expense amount/VAT');const row={...input,id:uid('expense'),createdAt:Date.now()};const state=this.read();state.expenses.push(row);this.write(state);invoiceStore.logFinanceActivity("EXPENSE_POSTED","expense",row.id,row.description,row);return row}
}
export const financeStore=new FinanceStore()
